version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  style_guide = "standard"
  environment = ["browser"]
  plugins = ["react"]

[[transformers]]
name = "standardjs"
enabled = true
