export const INIT_GROUP_LIST = 'INIT_GROUP_LIST';
export const ADD_ACTIVE_ITEM = 'ADD_ACTIVE_ITEM';
export const REMOVE_ACTIVE_ITEM = 'REMOVE_ACTIVE_ITEM';
export const UPDATE_ACTIVE_ITEM = 'UPDATE_ACTIVE_ITEM';
export const CLEAR_UNREAD = 'CLEAR_UNREAD';
export const SET_ONLINE = 'SET_ONLINE';