export const INIT_HISTORY = 'INIT_HISTORY'
export const ADD_HISTORY = 'ADD_HISTORY'
export const ADD_MESSAGE_ITEM = 'ADD_MESSAGE_ITEM'
export const SET_STATUS = 'SET_STATUS'
export const SET_FILE_SRC = 'SET_FILE_SRC'
