export const GROUP_FORM_SHOW = 'GROUP_FORM_SHOW';
export const SET_LOADING = 'SET_LOADING';
export const SELECT_LEFT_PANEL = 'SELECT_LEFT_PANEL';
export const TOGGLE_LEFT_PANEL = 'TOGGLE_LEFT_PANEL';
